# 2.1 Operaciones y transformaciones básicas

Este libro es para la parte de código de la [sección 2.1 de las notas](https://itam-ds.github.io/analisis-numerico-computo-cientifico/2.computo_matricial/2.1/Operaciones_y_transformaciones_basicas_del_Algebra_Lineal_Numerica.html)

# Tranformaciones de Gauss
## En vectores
**Ejemplo**:
<br>Considérese al vector $a=(-2,3,4)^T$. Definir una transformación de Gauss para hacer ceros por debajo de $a_1$ y otra transformación de Gauss para hacer cero a la entrada $a_3$.

In [1]:
import math
import numpy as np

np.set_printoptions(precision=3, suppress=True)

In [2]:
a = np.array([-2,3,4])

+ Para hacer ceros por debajo del **pivote** $a_1=-2$

>Se utiliza la definición $l_1=(0,\frac{a_2}{a_1},\frac{a_3}{a_1})^T$ así como el vectór canónico $e_1$, ya que se desea hacer ceras en las entradas debajo de la primera.

In [3]:
pivote = a[0]

#Transformación de Gauss
l1 = np.array([0, a[1]/pivote, a[2]/pivote]).T

#Vector canónico
e1 = np.array([1,0,0])

#Transformando
L1_a = a - l1*(e1@a)
L1_a

array([-2.,  0.,  0.])

A continuación se muestra que el producto $L_1 a$ es equivalente a lo anterior si se construye $L1$

In [4]:
L1 = np.eye(3) - np.outer(l1, e1)
L1

array([[1. , 0. , 0. ],
       [1.5, 1. , 0. ],
       [2. , 0. , 1. ]])

In [5]:
L1@a

array([-2.,  0.,  0.])

+ Para hacer ceros por debajo del **pivote** $a_2=3$

In [6]:
pivote = a[1]

#Transformación de Gauss
l2 = np.array([0, 0, a[2]/pivote]).T

#Vector canónico
e2 = np.array([0,1,0])

#Transformando
L2_a = a - l2*(e2@a)
L2_a

array([-2.,  3.,  0.])

A continuación se muestra que el producto $L_1 a$ es equivalente a lo anterior si se construye $L1$

In [7]:
L2 = np.eye(3) - np.outer(l2, e2)
L2

array([[ 1.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ],
       [ 0.   , -1.333,  1.   ]])

In [8]:
L2@a

array([-2.,  3.,  0.])

## En matrices

Utilizando $L_1$

In [9]:
A = np.array([[-1,2,5],
             [4,5,-7],
             [3,0,8]], dtype=float)
A

array([[-1.,  2.,  5.],
       [ 4.,  5., -7.],
       [ 3.,  0.,  8.]])

+ Para hacer ceros por debajo del **pivote** $a_{11}=-1$

In [11]:
pivote = A[0,0]

#Transformación de Gauss
l1 = np.array([0, A[1,0]/pivote, A[2,0]/pivote])

#Vector canónico
e2 = np.array([1,0,0])

#Transformando
L1_A1 = A[:,0] - l1*(e1@A[:,0])
L1_A1

array([-1.,  0.,  0.])

Y se debe aplicar $L_1$ a las columnas número 2 y 3 de $A$ para completar el producto $L_1A$

In [12]:
L1_A2 = A[:,1] - l1*(e1@A[:,1])
L1_A2

array([ 2., 13.,  6.])

In [13]:
L1_A3 = A[:,2] - l1*(e1@A[:,2])
L1_A3

array([ 5., 13., 23.])

A continuación se muesta que el producto $L_1A$ si se construye $L_1$ es equivalente a lo anterior

In [14]:
L1 = np.eye(3) - np.outer(l1, e1)
L1@A

array([[-1.,  2.,  5.],
       [ 0., 13., 13.],
       [ 0.,  6., 23.]])

Al aplicar $L_1$ a la primer columna de $A$ **siempre** obtenemos ceros por debajo del pivote que en este caso es $a_{11}$.