In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

## $\mathbb{A}$ diagonalizable

In [2]:
A = np.array([[1,-4,-4],
              [8,-11,-8],
              [-8,8,5]], dtype=float)
A

array([[  1.,  -4.,  -4.],
       [  8., -11.,  -8.],
       [ -8.,   8.,   5.]])

Vectores y valores **característicos**

In [3]:
evalue, evector = np.linalg.eig(A)
evalue, evector

(array([ 1., -3., -3.]),
 array([[ 0.333, -0.717, -0.241],
        [ 0.667, -0.02 , -0.796],
        [-0.667, -0.697,  0.555]]))

Cálculo de la matriz $\mathbb{A}=\mathbb{X}\Lambda\mathbb{X}^{-1}$

In [4]:
X = evector
Lambda = np.diag(evalue)

X @ Lambda @ np.linalg.inv(X)

array([[  1.,  -4.,  -4.],
       [  8., -11.,  -8.],
       [ -8.,   8.,   5.]])

$\mathbb{A}$ es diagonalizable pues: $\mathbb{X}^{-1}\mathbb{A}\mathbb{X}=\Lambda$

Observamos que se regresa a la misma matriz diagonal $\Lambda$

In [5]:
np.linalg.inv(X) @ A @ X

array([[ 1.,  0., -0.],
       [-0., -3., -0.],
       [ 0., -0., -3.]])

In [6]:
Lambda

array([[ 1.,  0.,  0.],
       [ 0., -3.,  0.],
       [ 0.,  0., -3.]])

Sin embargo, $\mathbb{X}$ no necesariamente es una matriz ortogonal

In [7]:
X[:,0].dot(X[:,0])

0.9999999999999998

In [8]:
X[:,0].dot(X[:,1])

0.2117366284008177

## $\mathbb{A}$ simétrica

**Descomposición espectral**: $A = Q\Lambda Q^T$

**Ejemplo**:
<br>Matriz simétrica y descomposición espectral de la misma:

In [9]:
A = np.array([[5,4,2],
              [4,5,2],
              [2,2,2.0]])
A

array([[5., 4., 2.],
       [4., 5., 2.],
       [2., 2., 2.]])

In [10]:
evalue, evector = np.linalg.eigh(A)
evalue, evector

(array([ 1.,  1., 10.]),
 array([[ 0.482,  0.569,  0.667],
        [-0.727, -0.166,  0.667],
        [ 0.49 , -0.806,  0.333]]))

Descomposición espectral, se verifica que el producto $Q\Lambda Q^T$ coincide con la matriz

In [11]:
Lambda = np.diag(evalue)
Q = evector

Q @ Lambda @ Q.T

array([[5., 4., 2.],
       [4., 5., 2.],
       [2., 2., 2.]])

$A$ es diagonalizable pues: $Q^TAQ=\Lambda$

Obsérvese que se llegan a los mismo valores `[1, 1, 10]` de la función `np.linalg.eigh()`

In [12]:
Q.T @ A @ Q

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0., 10.]])

# Similitud

In [13]:
A = np.array([[-1, -1 , -1, -1],
              [0, -5, -16, -22],
              [0, 3, 10, 14],
              [4, 8, 12, 14.0]])
A

array([[ -1.,  -1.,  -1.,  -1.],
       [  0.,  -5., -16., -22.],
       [  0.,   3.,  10.,  14.],
       [  4.,   8.,  12.,  14.]])

In [14]:
X1 = np.array([[2, -1, 0, 0],
              [-1, 2, -1, 0],
              [0, -1, 2, -1],
              [0, 0, -1, 1.0]])
X1

array([[ 2., -1.,  0.,  0.],
       [-1.,  2., -1.,  0.],
       [ 0., -1.,  2., -1.],
       [ 0.,  0., -1.,  1.]])

$B_1=X_1^{-1}AX_1$

Calculamos $B_1$ explícitamente para revisar qué forma tiene

In [15]:
B1 = np.linalg.inv(X1) @ A @ X1
B1

array([[ 1.,  2., -0.,  0.],
       [ 3.,  4., -0.,  0.],
       [ 0., -0.,  5.,  6.],
       [ 0., -0.,  7.,  8.]])

$B_2=X_2^{-1}AX_2$

Calculamos $B_1$ explícitamente para revisar qué forma tiene

In [16]:
X2 = np.array([[2, -1, 1, 0],
               [-1, 2, 0, 0],
               [0, -1, 0, 0],
               [0, 0, 0, 1.0]])

B2 = np.linalg.inv(X2) @ A @ X2
B2

array([[  1.,   2.,   0.,  -6.],
       [  3.,   4.,   0., -14.],
       [  0.,   0.,  -1.,  -3.],
       [  0.,   0.,   4.,  14.]])

$B_1$ y $B_2$ son entonces similares a $A$, por tanto tienen los mismo valores característicos

In [23]:
evalue, evector = np.linalg.eig(A)
evalue

array([13.152,  5.372, -0.152, -0.372])

In [20]:
evalue_B1, evector_B1 = np.linalg.eig(B1)
evalue_B1

array([ 5.372, -0.372, 13.152, -0.152])

In [21]:
evalue_B2, evector_B2 = np.linalg.eig(B2)
evalue_B2

array([-0.372,  5.372, -0.152, 13.152])

Los vectores característicos **no son los mismos** aunque las matrices sean similares, pero pueden obtenerse vía multiplicación de matrices

In [25]:
evector, evector_B1, evector_B2

(array([[-0.   , -0.046, -0.   , -0.736],
        [-0.806,  0.838, -0.281,  0.65 ],
        [ 0.517, -0.543,  0.804, -0.188],
        [ 0.289,  0.   , -0.523, -0.   ]]),
 array([[ 0.416, -0.825, -0.   ,  0.   ],
        [ 0.909,  0.566, -0.   , -0.   ],
        [ 0.   ,  0.   ,  0.593, -0.759],
        [ 0.   , -0.   ,  0.805,  0.651]]),
 array([[-0.825, -0.416,  0.537,  0.357],
        [ 0.566, -0.909,  0.326,  0.811],
        [ 0.   ,  0.   , -0.749,  0.096],
        [ 0.   ,  0.   ,  0.212, -0.453]]))

Como $A$ tiene eigenvalores distintos entonces es diagonalizable, esto es existen $X_3,\Lambda$ tales que $X_3^{-1}AX_3=\Lambda$

In [27]:
X_3 = evector
Lambda = np.diag(evalue)

Lambda

array([[13.152,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  5.372,  0.   ,  0.   ],
       [ 0.   ,  0.   , -0.152,  0.   ],
       [ 0.   ,  0.   ,  0.   , -0.372]])

In [28]:
np.linalg.inv(X_3) @ A @ X_3

array([[13.152, -0.   , -0.   ,  0.   ],
       [ 0.   ,  5.372, -0.   ,  0.   ],
       [-0.   ,  0.   , -0.152,  0.   ],
       [-0.   ,  0.   , -0.   , -0.372]])